max_epochs: 2000
devices: [0]
gpu: 'cuda:0'
checkpoint_tosave: 10
checkpoint_toload: 209
lr: 3.0
warmup_epochs: 200
warmup_lr: 1e-4
weight_decay: 1e-4

batch_size: 1024
num_workers: 16
knn_k: 200

temperature: 0.3
normalization: True
